version: '3.1'

services:
  boggle-board-generator:
    build:
      context: ./boggle-board-generator
      target: final
    ports:
      - 1729:1729
    restart: always
    networks:
      - boggle-network
    environment:
      WORDS_PATH: /bin/words.txt
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes :
      - mongodb_data:/data/db
    networks:
      - boggle-network

  redis: 
    image: redis
    restart: always
    networks:
      - boggle-network
    ports: 
      - "6379:6379"

  boggle-game-sync:
    build: ./boggle-game-sync
    ports:
      - "4000:4000"
    networks:
      - boggle-network
    depends_on:
      - redis
  
  boggle-game-server:
    build: ./boggle-game-server
    ports: 
      - "3003:3003"
    restart: always
    environment:
      - DICTIONARY_APP_API_URL=http://boggle-game-server:3003  # Internal service communication
    depends_on:
      - mongodb
      - boggle-game-sync
      - boggle-board-generator
    networks:
      - boggle-network
  
  boggle-game-app:
    build: ./boggle-game-app
    restart: always
    ports : 
      - "3717:3000"
    volumes:
      - /app/node-modules
      - ./boggle-game-app:/app
    environment:
      - UI_URL=http://boggle-game-app:3000  # Internal service communication
      - NEXTAUTH_URL=http://localhost:3717
    depends_on:
      - boggle-game-server
    networks:
      - boggle-network
networks:
  boggle-network:
    driver: bridge
volumes:
  mongodb_data: