version: '3'

services:
  dictionary-service:
    build: ./dictionary-service
    ports: 
      - "3003:3003"

    environment:
      - DICTIONARY_APP_API_URL=http://dictionary-service:3003  # Internal service communication
    networks:
      - boggle-network
  
  session-service:
    build: ./boggle-session-server
    ports:
      - "4000:4000"
    volumes:
      - /app/node-modules
      - ./dictionary-service:/src
    environment:
      - SESSION_APP_API_URL=http://localhost:4000  # Internal service communication
    networks:
      - boggle-network

  ui:
    build: ./boggle-game
    ports : 
      - "3717:3000"
    volumes:
      - /app/node-modules
      - ./boggle-game:/app
    environment:
      - UI_URL=http://ui:3000  # Internal service communication
    depends_on:
      - dictionary-service
      - session-service
    networks:
      - boggle-network
networks:
  boggle-network:
    driver: bridge