[package]
name = "boggle-board-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boggle-maker = "0.1.1"
genetic_algorithm = "0.18.1"
rand = "0.9.0"
word-trie = "0.1.0"
